# Выбираем контейнер с необходимыми Rust компонентами
os: PyCharm Community Edition 2022.1.2

# Устанавливаем Rust
install:
  # Скачиваем rustup
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  # Устанавливаем стабильный Rust с MSVC ABI
  # Если хотите другую версию - замените stable на версию
  # Если хотите GNU ABI - замените x86_64-pc-windows-msvc на x86_64-pc-windows-gnu
  - rustup-init -yv --default-toolchain stable --default-host x86_64-pc-windows-msvc
  # Устанавливаем пути до компонентов Rust
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  # Выводим версии
  - rustc -vV
  - cargo -vV

# Выключаем стандартный сборщик AppVeyor
build: false

# Используем специальный тестовый скрипт
test_script:
  # Собираем
  - cargo build --verbose
  # Запускаем тесты
  - cargo test --verbose
language: python 
before_install: 
 - chmod +x ./flaskapp/st.sh 
install: 
 - pip3 install flask 
 - pip3 install gunicorn 
 - pip3 install requests 
 - pip3 install flask-bootstrap 
 - pip3 install flask-wtf
 - pip3 install pillow 
 - pip3 install tensorflow==2.0.0-alpha0 
 - pip3 install keras 
script: 
 - cd flaskapp
 - ./st.sh
